#!/bin/bash
mkdir ../Data
mono bin/Debug/net40/IFix.exe -inject bin/Debug/net40/IFix.Core.dll bin/Debug/net40/IFix.TestDLL.Redirect.dll no_cfg ../Data/IFix.TestDLL.Redirect.dif ../Data/IFix.TestDLL.Redirect.dll
